In [32]:
#Question 1
import numpy as np
print(np.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [34]:
#Question 2
a = []
b = []
for i in range(5):
    a.append(int(input()))
for j in range(5):
    b.append(int(input()))
#covert
a = np.array(a)
b = np.array(b)
c = np.concatenate((a, b))
print(c)
print(np.sort(c))

90
76
54
43
54
43
32
21
0
1
[90 76 54 43 54 43 32 21  0  1]
[ 0  1 21 32 43 43 54 54 76 90]


In [35]:
#Question 3
arr = np.arange(12).reshape((3, 4))
print(arr) #ndarray
#dimentions
print(arr.ndim)
#size
print(arr.size)
#shape
print(arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12
(3, 4)


In [36]:
#Question 4
n = np.arange(10)
#np.newaxis
print(n[np.newaxis,:])
#The following is equivalent to x[np.newaxis, :] or x[np.newaxis]:
print(np.expand_dims(n,axis=0))

[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
